trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: geeklearningio.gl-vsts-tasks-yarn.yarn-installer-task.YarnInstaller@2
  displayName: 'Use Yarn 1.x'
- task: geeklearningio.gl-vsts-tasks-yarn.yarn-task.Yarn@2
  displayName: 'Yarn Install'
  inputs:
    ProjectDirectory: web
- task: geeklearningio.gl-vsts-tasks-yarn.yarn-task.Yarn@2
  displayName: 'Build Angular App'
  inputs:
    ProjectDirectory: web
    Arguments: 'ng build --prod'
- task: Docker@2
  inputs:
    command: 'build'
    Dockerfile: './docker/Dockerfile'